CREATE OR REPLACE TABLE `local-bliss-359814.wherehouse.dados_openwhather` AS
SELECT
  city,
  city_id,
  coord_lon,
  coord_lat,
  weather_id,
  weather_main,
  weather_description,
  weather_icon,
  base,
  main_temp,
  main_feels_like,
  main_temp_min,
  main_temp_max,
  main_pressure,
  main_humidity,
  main_sea_level,
  main_grnd_level,
  visibility,
  wind_speed,
  wind_deg,
  wind_gust,
  clouds_all,
  rain_1h,
  rain_3h,
  snow_1h,
  snow_3h,
  dt,
  CAST(sys_type AS FLOAT64) AS sys_type,
  CAST(sys_id AS FLOAT64) AS sys_id,
  sys_country,
  sys_sunrise,
  sys_sunset,
  timezone_offset,
  cod,
  timestamp_utc
FROM `local-bliss-359814.wherehouse.dados_openwhather`;
